const PREFIX = 'native.calendar';

module.exports = {
  CHANGE_MONTH_LEFT_ARROW: `${PREFIX}.CHANGE_MONTH_LEFT_ARROW`,
  CHANGE_MONTH_RIGHT_ARROW: `${PREFIX}.CHANGE_MONTH_RIGHT_ARROW`,
  CHANGE_MONTH_LEFT_DOUBLE_ARROW: `${PREFIX}.CHANGE_MONTH_LEFT_DOUBLE_ARROW`,
  CHANGE_MONTH_RIGHT_DOUBLE_ARROW: `${PREFIX}.CHANGE_MONTH_RIGHT_DOUBLE_ARROW`,
  SELECT_DATE_SLOT: `${PREFIX}.SELECT_DATE_SLOT`
};
